=== cgonzalez7684/fegus/Documentacion/Archivo XML y XSD Credito Vrs 6 Credito 8-08-2025 (1)/Crédito/NEC2024_Garantias_Operacion.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Alexis Rodriguez (sugef) -->
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <!-- Bloque General-->
    <xs:element name="ArchivoSICVECA">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Encabezado" />
                <xs:element ref="Datos" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Bloque Encabezado-->
    <xs:element name="Encabezado">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ClaseDato" />
                <xs:element ref="VersionClaseDato" />
                <xs:element ref="Archivo" />
                <xs:element ref="VersionArchivo" />
                <xs:element ref="Periodo" />
                <xs:element ref="IdEntidad" />
                <xs:element ref="TipoCarga" />
                <xs:element ref="TipoMoneda" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ClaseDato">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="5" />
                <xs:pattern value="([0-9])+" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="VersionClaseDato">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:totalDigits value="10" />
                <xs:fractionDigits value="2" />
                <xs:pattern value="([0-9])+.[0-9][0-9]?" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Archivo">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="15" />
                <xs:pattern value="([0-9])+" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="VersionArchivo">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:totalDigits value="10" />
                <xs:fractionDigits value="2" />
                <xs:pattern value="([0-9])+.[0-9][0-9]?" />
                <xs:maxInclusive value="2.0" />
                <xs:minInclusive value="2.0" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Periodo">
        <xs:simpleType>
            <xs:restriction base="xs:token">
                <xs:length value="10" />
                <xs:pattern value="([0][1-9][/][0][1-9][/][0-2][0-9][0-9][0-9])?" />
                <xs:pattern value="([0][1-9][/][1][0-2][/][0-2][0-9][0-9][0-9])?" />
                <xs:pattern value="([1-2][0-9][/][0][1-9][/][0-2][0-9][0-9][0-9])?" />
                <xs:pattern value="([1-2][0-9][/][1][0-2][/][0-2][0-9][0-9][0-9])?" />
                <xs:pattern value="([3][0-1][/][0][1-9][/][0-2][0-9][0-9][0-9])?" />
                <xs:pattern value="([3][0-1][/][1][0-2][/][0-2][0-9][0-9][0-9])?" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="IdEntidad">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="30" />
                <xs:minLength value="1" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="TipoCarga">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="2" />
                <xs:pattern value="([0-9])+" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="TipoMoneda">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="6" />
                <xs:pattern value="([0-9])+" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <!-- Bloque Datos-->
    <xs:element name="Datos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Registro" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Registro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TipoPersonaDeudor" minOccurs="1" />
                <xs:element ref="IdDeudor" minOccurs="1" />
                <xs:element ref="IdOperacionCredito" minOccurs="1" />
                <xs:element ref="TipoGarantia" minOccurs="1" />
                <xs:element ref="IdGarantia" minOccurs="1" />
                <xs:element ref="IndicadorFormaTraspasoBien" minOccurs="1"/>
                <xs:element ref="IdGarantiaTraspaso" minOccurs="1" />
                <xs:element ref="TipoMitigador" minOccurs="1" />
                <xs:element ref="TipoDocumentoLegal" minOccurs="1" />
                <xs:element ref="ValorAjustadoGarantia" minOccurs="1" />
                <xs:element ref="TipoInscripcionGarantia" minOccurs="1" />
                <xs:element ref="FechaPresentacionRegistroGarantia" minOccurs="0"/>
                <xs:element ref="PorcentajeResponsabilidadGarantia" minOccurs="1" />
                <xs:element ref="ValorNominalGarantia" minOccurs="1" />
                <xs:element ref="TipoMonedaValorNominalGarantia" minOccurs="0"/>
                <xs:element ref="FechaConstitucionGarantia" minOccurs="0"/>
                <xs:element ref="FechaVencimientoGarantia" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required" />
            <xs:attribute name="accion" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1" />
                        <xs:enumeration value="insertar" />
                        <xs:enumeration value="modificar" />
                        <xs:enumeration value="eliminar" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="Empty">
        <xs:restriction base="xs:string">
            <xs:enumeration value=""/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="TipoPersonaDeudor">
        <xs:simpleType>
            <xs:restriction base="xs:integer" >
                <xs:totalDigits value="2"/>
				<xs:enumeration value="1" />
				<xs:enumeration value="2" />
				<xs:enumeration value="3" />
				<xs:enumeration value="4" />
				<xs:enumeration value="5" />
				<xs:enumeration value="6" />
				<xs:enumeration value="13" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="IdDeudor">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
                <xs:maxLength value="30"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="IdOperacionCredito">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
                <xs:maxLength value="25"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="TipoGarantia">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="5"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="IdGarantia">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
                <xs:maxLength value="25"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="IndicadorFormaTraspasoBien">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1" />
				<xs:enumeration value="0" />
                <xs:enumeration value="1" />
                <xs:enumeration value="2" />
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="IdGarantiaTraspaso">
        <xs:simpleType>
            <xs:restriction base="xs:string" >
                <xs:minLength value="1"/>
                <xs:maxLength value="25"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="TipoMitigador">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
                <xs:totalDigits value="2"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="TipoDocumentoLegal">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
                <xs:totalDigits value="2"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="ValorAjustadoGarantia">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:totalDigits value="22"/>
                <xs:fractionDigits value="2" />
                <xs:minInclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="TipoInscripcionGarantia">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="2"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="FechaPresentacionRegistroGarantia">
        <xs:simpleType>
            <xs:union memberTypes="Empty">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:length value="10"/>
                        <xs:pattern value="([0][1-9][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([0][1-9][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([1-2][0-9][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([1-2][0-9][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([3][0-1][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([3][0-1][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:union>
        </xs:simpleType>
    </xs:element>
    <xs:element name="PorcentajeResponsabilidadGarantia">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:totalDigits value="5"/>
                <xs:fractionDigits value="2" />
                <xs:maxInclusive value="100"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="ValorNominalGarantia">
        <xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:totalDigits value="20"/>
				<xs:minInclusive value="0"/>
			</xs:restriction>
        </xs:simpleType>
    </xs:element>
	<xs:element name="TipoMonedaValorNominalGarantia">
		<xs:simpleType>
			<xs:union>
				<xs:simpleType>
					 <xs:restriction base="xs:integer">
						<xs:totalDigits value="6"/>
					</xs:restriction>
				</xs:simpleType>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:union>
		</xs:simpleType>
	</xs:element>
    <xs:element name="FechaConstitucionGarantia">
        <xs:simpleType>
            <xs:union memberTypes="Empty">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:length value="10"/>
                        <xs:pattern value="([0][1-9][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([0][1-9][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([1-2][0-9][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([1-2][0-9][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([3][0-1][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([3][0-1][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:union>
        </xs:simpleType>
    </xs:element>
    <xs:element name="FechaVencimientoGarantia">
        <xs:simpleType>
            <xs:union memberTypes="Empty">
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:length value="10"/>
                        <xs:pattern value="([0][1-9][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([0][1-9][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([1-2][0-9][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([1-2][0-9][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([3][0-1][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
                        <xs:pattern value="([3][0-1][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:union>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== cgonzalez7684/fegus/Documentacion/Archivo XML y XSD Credito Vrs 6 Credito 8-08-2025 (1)/Crédito/NEC2024_Garantias_Operacion.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<ArchivoSICVECA NS0:noNamespaceSchemaLocation="NEC2024_Garantias_Operacion.xsd" xmlns:NS0="http://www.w3.org/2001/XMLSchema-instance">
  <Encabezado>
    <ClaseDato>51</ClaseDato>
    <VersionClaseDato>1.0</VersionClaseDato>
    <Archivo>5113</Archivo>
    <VersionArchivo>2.0</VersionArchivo>
    <Periodo>01/01/2022</Periodo>
    <IdEntidad>3101192928</IdEntidad>
    <TipoCarga>1</TipoCarga>
    <TipoMoneda>1</TipoMoneda>
  </Encabezado>
  <Datos>
    <Registro id="" accion="">
      <TipoPersonaDeudor></TipoPersonaDeudor>
      <IdDeudor></IdDeudor>
      <IdOperacionCredito></IdOperacionCredito>
      <TipoGarantia></TipoGarantia>
      <IdGarantia></IdGarantia>
      <IndicadorFormaTraspasoBien></IndicadorFormaTraspasoBien>
      <IdGarantiaTraspaso></IdGarantiaTraspaso>
      <TipoMitigador></TipoMitigador>
      <TipoDocumentoLegal></TipoDocumentoLegal>
      <ValorAjustadoGarantia></ValorAjustadoGarantia>
      <TipoInscripcionGarantia></TipoInscripcionGarantia>
      <FechaPresentacionRegistroGarantia></FechaPresentacionRegistroGarantia>
      <PorcentajeResponsabilidadGarantia></PorcentajeResponsabilidadGarantia>
      <ValorNominalGarantia></ValorNominalGarantia>
      <TipoMonedaValorNominalGarantia></TipoMonedaValorNominalGarantia>
      <FechaConstitucionGarantia></FechaConstitucionGarantia>
      <FechaVencimientoGarantia></FechaVencimientoGarantia>
    </Registro>
  </Datos>
</ArchivoSICVECA>
