=== cgonzalez7684/fegus/Documentacion/Archivo XML y XSD Credito Vrs 6 Credito 8-08-2025 (1)/Crédito/NEC2024_Garantias_Mobiliarias.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <!-- Bloque General-->
    <xs:element name="ArchivoSICVECA">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Encabezado"/>
                <xs:element ref="Datos"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Bloque Encabezado-->
    <xs:element name="Encabezado">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ClaseDato"/>
                <xs:element ref="VersionClaseDato"/>
                <xs:element ref="Archivo"/>
                <xs:element ref="VersionArchivo"/>
                <xs:element ref="Periodo"/>
                <xs:element ref="IdEntidad"/>
                <xs:element ref="TipoCarga"/>
                <xs:element ref="TipoMoneda"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ClaseDato">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="5"/>
                <xs:pattern value="([0-9])+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="VersionClaseDato">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:totalDigits value="10"/>
                <xs:fractionDigits value="2"/>
                <xs:pattern value="([0-9])+.[0-9][0-9]?"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Archivo">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="15"/>
                <xs:pattern value="([0-9])+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="VersionArchivo">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:totalDigits value="10"/>
                <xs:fractionDigits value="2"/>
                <xs:pattern value="([0-9])+.[0-9][0-9]?"/>
                <xs:maxInclusive value="2.0"/>
                <xs:minInclusive value="2.0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Periodo">
        <xs:simpleType>
            <xs:restriction base="xs:token">
                <xs:length value="10"/>
                <xs:pattern value="([0][1-9][/][0][1-9][/][0-2][0-9][0-9][0-9])?"/>
                <xs:pattern value="([0][1-9][/][1][0-2][/][0-2][0-9][0-9][0-9])?"/>
                <xs:pattern value="([1-2][0-9][/][0][1-9][/][0-2][0-9][0-9][0-9])?"/>
                <xs:pattern value="([1-2][0-9][/][1][0-2][/][0-2][0-9][0-9][0-9])?"/>
                <xs:pattern value="([3][0-1][/][0][1-9][/][0-2][0-9][0-9][0-9])?"/>
                <xs:pattern value="([3][0-1][/][1][0-2][/][0-2][0-9][0-9][0-9])?"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="IdEntidad">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:maxLength value="30"/>
                <xs:minLength value="1"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="TipoCarga">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="2"/>
                <xs:pattern value="([0-9])+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="TipoMoneda">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="6"/>
                <xs:pattern value="([0-9])+"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <!-- Bloque Datos-->
    <xs:element name="Datos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Registro" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Registro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="IdGarantiaMobiliaria" minOccurs="1"/>
                <xs:element ref="FechaPublicidadGM" minOccurs="1"/>
                <xs:element ref="MontoGarantiaMobiliaria" minOccurs="1"/>
                <xs:element ref="FechaVencimientoGM" minOccurs="1"/>
                <xs:element ref="FechaMontoReferencia" minOccurs="1"/>
                <xs:element ref="MontoReferencia" minOccurs="1"/>
                <xs:element ref="TipoMonedaMontoReferencia" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
            <xs:attribute name="accion" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                        <xs:enumeration value="insertar"/>
                        <xs:enumeration value="modificar"/>
                        <xs:enumeration value="eliminar"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="FormatoFecha">
        <xs:restriction base="xs:token">
            <xs:length value="10"/>
            <xs:pattern value="([0][1-9][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
            <xs:pattern value="([0][1-9][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
            <xs:pattern value="([1-2][0-9][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
            <xs:pattern value="([1-2][0-9][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
            <xs:pattern value="([3][0-1][/][0][1-9][/][1-2][0-9][0-9][0-9])?"/>
            <xs:pattern value="([3][0-1][/][1][0-2][/][1-2][0-9][0-9][0-9])?"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="IdGarantiaMobiliaria">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="1"/>
                <xs:maxLength value="25"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="FechaPublicidadGM">
        <xs:simpleType>
            <xs:union memberTypes="FormatoFecha"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="MontoGarantiaMobiliaria">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:totalDigits value="22"/>
                <xs:fractionDigits value="2"/>
                <xs:minInclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="FechaVencimientoGM">
        <xs:simpleType>
            <xs:union memberTypes="FormatoFecha"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="FechaMontoReferencia">
        <xs:simpleType>
            <xs:union memberTypes="FormatoFecha"/>
        </xs:simpleType>
    </xs:element>
    <xs:element name="MontoReferencia">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:totalDigits value="22"/>
                <xs:fractionDigits value="2" />
                <xs:minInclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="TipoMonedaMontoReferencia">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="6"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
</xs:schema>

=== cgonzalez7684/fegus/Documentacion/Archivo XML y XSD Credito Vrs 6 Credito 8-08-2025 (1)/Crédito/NEC2024_Garantias_Mobiliarias.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<ArchivoSICVECA NS0:noNamespaceSchemaLocation="NEC2024_Garantias_Mobiliarias.xsd" xmlns:NS0="http://www.w3.org/2001/XMLSchema-instance">
  <Encabezado>
    <ClaseDato>51</ClaseDato>
    <VersionClaseDato>1.0</VersionClaseDato>
    <Archivo>5122</Archivo>
    <VersionArchivo>2.0</VersionArchivo>
    <Periodo>01/01/2022</Periodo>
    <IdEntidad>3101192928</IdEntidad>
    <TipoCarga>1</TipoCarga>
    <TipoMoneda>1</TipoMoneda>
  </Encabezado>
  <Datos>
    <Registro id="" accion="">
      <IdGarantiaMobiliaria></IdGarantiaMobiliaria>
      <FechaPublicidadGM></FechaPublicidadGM>
      <MontoGarantiaMobiliaria></MontoGarantiaMobiliaria>
      <FechaVencimientoGM></FechaVencimientoGM>
      <FechaMontoReferencia></FechaMontoReferencia>
      <MontoReferencia></MontoReferencia>
      <TipoMonedaMontoReferencia></TipoMonedaMontoReferencia>
    </Registro>
  </Datos>
</ArchivoSICVECA>
